# Generated by Django 4.2.2 on 2023-06-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_review_alter_watchlist_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='watchlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.watchlist'),
        ),
    ]
